name: tests

on: push

defaults:
  run:
    shell: bash -leo pipefail {0} # Removed " --noprofile --norc " options from default bash

jobs:
  build:
    name: build NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ 'gnu' ]
        model: [ 'ADCIRC' ]
        forcings: [ 'ATMESH WW3DATA' ]
    container:
      image: panvelissariou1/coastalapp:test2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
          # NOTE: this token is attached to a specific GitHub account (@zacharyburnettNOAA) because it has permission to clone the `adcirc-cg` repo, which is private.
          # Perhaps in the future we can use the token from a dummy account, and / or an SSH key?
          # The token is currently stored in the repository Secrets; it can be updated at https://github.com/noaa-ocs-modeling/CoastalApp/settings/secrets/actions
          token: ${{ secrets.PULL_TOKEN }}
      - name: run build script
        run: ./build.sh -y -compiler ${{ matrix.compiler }} -platform linux -component "${{ matrix.model }} ${{ matrix.forcings }}"
      - name: save built binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.compiler }} ${{ matrix.model }} ${{ matrix.forcings }}
          path: |
            ./ALLBIN_INSTALL/adcprep
            ./ALLBIN_INSTALL/NEMS.x
  test:
    needs: build
    name: test NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test: shinnecock_atmesh_adcirc
            compiler: 'gnu'
            model: 'ADCIRC'
            forcings: 'ATMESH WW3DATA'
    container:
      image: panvelissariou1/coastalapp:test1
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: noaa-ocs-modeling/CoastalApp-testsuite
          path: ${{ github.workspace }}/CoastalApp-testsuite
      - name: download binaries
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ matrix.compiler }} ${{ matrix.model }} ${{ matrix.forcings }}
          path: ${{ github.workspace }}/CoastalApp-testsuite
      - name: test
        run: |
          source /etc/profile.d/modules.sh
          source modulefiles/envmodules_gnu.linux
          cd ${{ github.workspace }}/CoastalApp-testsuite
          cd ${{ matrix.test }}
          ../NEMS.x

