name: tests

on: push

defaults:
  run:
    # Removed " --noprofile --norc " options from default bash
    shell: bash -lo pipefail {0}

jobs:
  build:
    name: build NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # define which sets of components to iterate through (a new job will be spawned for each matrix combination)
        components: [ 'ADCIRC ATMESH WW3DATA', 'ADCIRC PAHM WW3', 'SCHISM WW3', 'ADCIRC SCHISM PAHM WW3 ATMESH WW3DATA' ]
        compiler: [ 'gnu' ]
    container:
      image: panvelissariou1/coastalapp:test2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
          # NOTE: this token is attached to a specific GitHub account (@zacharyburnettNOAA) because it has permission to clone the `adcirc-cg` repo, which is private.
          # Perhaps in the future we can use the token from a dummy account, and / or an SSH key?
          # The token is currently stored in the repository Secrets; it can be updated at https://github.com/noaa-ocs-modeling/CoastalApp/settings/secrets/actions
          token: ${{ secrets.PULL_TOKEN }}
      - name: run build script
        run: ./build.sh --compiler ${{ matrix.compiler }} --platform linux --component "${{ matrix.components }}" -y
      - name: save built binaries
        uses: actions/upload-artifact@v2
        with:
          name: NEMS-${{ matrix.compiler }}-${{ matrix.components }}
          path: ${{ github.workspace }}/ALLBIN_INSTALL/*
  test:
    needs: build
    name: test NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # define the tests to iterate through
        test: [ 'shinnecock_atmesh_adcirc' ]
        compiler: [ 'gnu' ]
        # define the components required for each test
        include:
          - test: 'shinnecock_atmesh_adcirc'
            components: 'ADCIRC ATMESH WW3DATA'
    container:
      image: panvelissariou1/coastalapp:test2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: noaa-ocs-modeling/CoastalApp-testsuite
          path: CoastalApp-testsuite
      - name: download binaries
        uses: actions/download-artifact@v3.0.0
        with:
          name: NEMS-${{ matrix.compiler }}-${{ matrix.components }}
          path: ALLBIN_INSTALL/
      - name: ensure that binaries are executable
        run: chmod +x ALLBIN_INSTALL/*
      - name: run "${{ matrix.test }}" test case
        run: |
          # move into test directory
          cd CoastalApp-testsuite/${{ matrix.test }}
          
          # source modules needed to run NEMS
          source ../../modulefiles/envmodules_${{ matrix.compiler }}.linux
          
          # partition mesh
          ../../ALLBIN_INSTALL/adcprep --np 2 --partmesh
          ../../ALLBIN_INSTALL/adcprep --np 2 --prepall
          
          # run NEMS
          ../../ALLBIN_INSTALL/NEMS.x
