name: tests

on: push

defaults:
  run:
    # Removed " --noprofile --norc " options from default bash
    shell: bash -leo pipefail {0}

jobs:
  build:
    name: build NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ 'gnu' ]
    container:
      image: panvelissariou1/coastalapp:test2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
          # NOTE: this token is attached to a specific GitHub account (@zacharyburnettNOAA) because it has permission to clone the `adcirc-cg` repo, which is private.
          # Perhaps in the future we can use the token from a dummy account, and / or an SSH key?
          # The token is currently stored in the repository Secrets; it can be updated at https://github.com/noaa-ocs-modeling/CoastalApp/settings/secrets/actions
          token: ${{ secrets.PULL_TOKEN }}
      - name: run build script
        run: ./build.sh -y -compiler ${{ matrix.compiler }} -platform linux -component "ADCIRC ATMESH WW3DATA"
      - name: save built binaries
        uses: actions/upload-artifact@v2
        with:
          name: NEMS-${{ matrix.compiler }}
          path: ${{ github.workspace }}/ALLBIN_INSTALL/*
  test:
    needs: build
    name: test NEMS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ 'gnu' ]
        test: [ 'shinnecock_atmesh_adcirc' ]
    container:
      image: panvelissariou1/coastalapp:test2
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: zacharyburnettNOAA/CoastalApp-testsuite
          path: CoastalApp-testsuite
      - name: download binaries
        uses: actions/download-artifact@v3.0.0
        with:
          name: NEMS-${{ matrix.compiler }}
          path: ALLBIN_INSTALL/
      - name: run "${{ matrix.test }}" test case
        run: |
          chmod +x ALLBIN_INSTALL/*
          source modulefiles/envmodules_${{ matrix.compiler }}.linux
          cd CoastalApp-testsuite
          cd ${{ matrix.test }}
          ../../ALLBIN_INSTALL/adcprep --np 11 --partmesh
          ../../ALLBIN_INSTALL/adcprep --np 11 --prepall
          ../../ALLBIN_INSTALL/NEMS.x
